# EI01: ¿Cuál es la cantidad total de un contaminante emitido por cada ciudad? / What is the total amount of a pollutant emitted by each city?

PREFIX eio:    <http://w3id.org/def/emissionsInventoryOntology#>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX saref:  <https://saref.etsi.org/core/>
PREFIX s4city: <https://saref.etsi.org/saref4city/>

SELECT ?city ?cityLabel ?unit (SUM(xsd:decimal(?value)) AS ?totalEmittedAmount)

WHERE {
    VALUES ?pollutant {
        eio:CO2Scope1Emissions
    }

    ?emissionData
        rdf:type s4city:KeyPerformanceIndicatorAssessment ;
        s4city:quantifiesKPI ?pollutant ;
        s4city:refersToFeature ?city ;
        saref:hasValue ?value ;
        saref:isMeasuredIn ?unit .

    ?city rdf:type s4city:City .

    OPTIONAL {
        ?city rdfs:label ?cityLabel .
        FILTER( LANG(?cityLabel) != "")
    }
}
GROUP BY ?city ?cityLabel ?unit
ORDER BY ?cityLabel