# EI03: ¿Cuáles son las emisiones correspondientes a un sector determinado? / What emissions correspond to a given sector?

PREFIX eio:    <http://w3id.org/def/emissionsInventoryOntology#>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX saref:  <https://saref.etsi.org/core/>
PREFIX s4city: <https://saref.etsi.org/saref4city/>

SELECT ?pollutant ?pollutantLabel ?value ?unit

WHERE {
    VALUES ?sector {
        eio:Transport
    }

    ?sector rdf:type eio:Sector .

    ?emissionData
        rdf:type s4city:KeyPerformanceIndicatorAssessment ;
        eio:refersToSector ?sector ;
        s4city:quantifiesKPI ?pollutant ;
        saref:hasValue ?value ;
        saref:isMeasuredIn ?unit .

    OPTIONAL {
        ?pollutant rdfs:label ?pollutantLabel .
        FILTER(
            LANG(?pollutantLabel) = "en" ||
            LANG(?pollutantLabel) = "es"
        )
    }
}
ORDER BY ?pollutantLabel