# EI06: ¿Cuáles son los subsectores directos de un sector? / What are the direct subsectors of a given sector?

PREFIX eio:  <http://w3id.org/def/emissionsInventoryOntology#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?subsector ?subsectorLabel
WHERE {
    VALUES ?sector {
        eio:Transport
    }

    ?sector rdf:type eio:Sector .

    ?subsector
        rdf:type eio:Sector ;
        skos:broader ?sector .

    OPTIONAL {
        ?subsector rdfs:label ?subsectorLabel .
        FILTER(
            LANG(?subsectorLabel) = "en" ||
            LANG(?subsectorLabel) = "es"
        )
    }
}
ORDER BY ?subsectorLabel

