# EI07: ¿Cuáles son las emisiones agregadas de un sector, incluyendo las emisiones de todos sus subsectores, durante un periodo determinado? / What are the aggregated emissions of a given sector, including the emissions of all its subsectors, during a given period?

PREFIX eio:    <http://w3id.org/def/emissionsInventoryOntology#>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX time:   <http://www.w3.org/2006/time#>
PREFIX saref:  <https://saref.etsi.org/core/>
PREFIX s4city: <https://saref.etsi.org/saref4city/>

SELECT ?includedSector ?includedSectorLabel ?pollutant ?pollutantLabel ?unit (SUM(xsd:decimal(?value)) AS ?sectorEmissionAmount)

WHERE {
    VALUES ?mainSector {
        eio:Transport
    }

    VALUES ?year {
        "2024"^^xsd:gYear
    }

    ?mainSector rdf:type eio:Sector .

    ?includedSector
        rdf:type eio:Sector ;
        skos:broader* ?mainSector .

    ?emissionData
        rdf:type s4city:KeyPerformanceIndicatorAssessment ;
        eio:refersToSector ?includedSector ;
        s4city:quantifiesKPI ?pollutant ;
        s4city:refersToTime ?period ;
        saref:hasValue ?value ;
        saref:isMeasuredIn ?unit .

    ?period
        rdf:type time:DateTimeInterval ;
        time:hasDateTimeDescription ?dateTimeDescription .

    ?dateTimeDescription
        rdf:type time:DateTimeDescription ;
        time:year ?year .

    OPTIONAL {
        ?includedSector rdfs:label ?includedSectorLabel .
        FILTER(
            LANG(?includedSectorLabel) = "en" ||
            LANG(?includedSectorLabel) = "es"
        )
    }

    OPTIONAL {
        ?pollutant rdfs:label ?pollutantLabel .
        FILTER(
            LANG(?pollutantLabel) = "en" ||
            LANG(?pollutantLabel) = "es"
        )
    }
}
GROUP BY ?includedSector ?includedSectorLabel ?pollutant ?pollutantLabel ?unit
ORDER BY ?includedSectorLabel ?pollutantLabel