# EI08: ¿Cuáles son las emisiones de un contaminante durante un año determinado? / What are the emissions of a given pollutant during a given year?

PREFIX eio:    <http://w3id.org/def/emissionsInventoryOntology#>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX time:   <http://www.w3.org/2006/time#>
PREFIX saref:  <https://saref.etsi.org/core/>
PREFIX s4city: <https://saref.etsi.org/saref4city/>

SELECT ?sector ?sectorLabel ?geographicalFeature ?geographicalFeatureLabel ?value ?unit
WHERE {
    VALUES ?pollutant {
        eio:CO2Scope1Emissions
    }

    VALUES ?year {
        "2023"^^xsd:gYear
    }

    ?emissionData
        rdf:type s4city:KeyPerformanceIndicatorAssessment ;
        s4city:quantifiesKPI ?pollutant ;
        s4city:refersToTime ?period ;
        saref:hasValue ?value ;
        saref:isMeasuredIn ?unit .

    ?period
        rdf:type time:DateTimeInterval ;
        time:hasDateTimeDescription ?dateTimeDescription .

    ?dateTimeDescription
        rdf:type time:DateTimeDescription ;
        time:year ?year .

    OPTIONAL {
        ?emissionData eio:refersToSector ?sector .

        OPTIONAL {
            ?sector rdfs:label ?sectorLabel .
            FILTER(
                LANG(?sectorLabel) = "en" ||
                LANG(?sectorLabel) = "es"
            )
        }
    }

    OPTIONAL {
        ?emissionData
            s4city:refersToFeature ?geographicalFeature .

        OPTIONAL {
            ?geographicalFeature
                rdfs:label ?geographicalFeatureLabel .

            FILTER(
                LANG(?geographicalFeatureLabel) = "en" ||
                LANG(?geographicalFeatureLabel) = "es"
            )
        }
    }
}
ORDER BY ?sectorLabel ?geographicalFeatureLabel


