# EI09: ¿Qué sector ha experimentado el mayor incremento o la mayor reducción de emisiones entre dos periodos? / Which sector experienced the greatest increase or the greatest decrease in emissions between two given periods?

PREFIX eio:    <http://w3id.org/def/emissionsInventoryOntology#>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX time:   <http://www.w3.org/2006/time#>
PREFIX saref:  <https://saref.etsi.org/core/>
PREFIX s4city: <https://saref.etsi.org/saref4city/>

SELECT ?sector ?sectorLabel ?unit ?initialEmissionAmount ?finalEmissionAmount (?finalEmissionAmount - ?initialEmissionAmount AS ?emissionChange)

WHERE {
    {
        SELECT ?sector ?unit (SUM(xsd:decimal(?initialValue)) AS ?initialEmissionAmount)
        
        WHERE {
            VALUES ?pollutant {
                eio:CO2Scope1Emissions
            }

            VALUES ?initialYear {
                "2023"^^xsd:gYear
            }

            ?initialEmissionData
                rdf:type s4city:KeyPerformanceIndicatorAssessment ;
                s4city:quantifiesKPI ?pollutant ;
                eio:refersToSector ?sector ;
                s4city:refersToTime ?initialPeriod ;
                saref:hasValue ?initialValue ;
                saref:isMeasuredIn ?unit .

            ?initialPeriod
                rdf:type time:DateTimeInterval ;
                time:hasDateTimeDescription ?initialDescription .

            ?initialDescription
                rdf:type time:DateTimeDescription ;
                time:year ?initialYear .
        }
        GROUP BY ?sector ?unit
    }

    {
        SELECT ?sector ?unit (SUM(xsd:decimal(?finalValue)) AS ?finalEmissionAmount)
        
        WHERE {
            VALUES ?pollutant {
                eio:CO2Scope1Emissions
            }

            VALUES ?finalYear {
                "2024"^^xsd:gYear
            }

            ?finalEmissionData
                rdf:type s4city:KeyPerformanceIndicatorAssessment ;
                s4city:quantifiesKPI ?pollutant ;
                eio:refersToSector ?sector ;
                s4city:refersToTime ?finalPeriod ;
                saref:hasValue ?finalValue ;
                saref:isMeasuredIn ?unit .

            ?finalPeriod
                rdf:type time:DateTimeInterval ;
                time:hasDateTimeDescription ?finalDescription .

            ?finalDescription
                rdf:type time:DateTimeDescription ;
                time:year ?finalYear .
        }
        GROUP BY ?sector ?unit
    }

    OPTIONAL {
        ?sector rdfs:label ?sectorLabel .
        FILTER(
            LANG(?sectorLabel) = "en" ||
            LANG(?sectorLabel) = "es"
        )
    }
}
ORDER BY DESC(?emissionChange)