# EI11: ¿Qué ciudad presenta el mayor valor de emisión de un contaminante durante un periodo determinado? / Which city has the highest emission value for a given pollutant during a given period?

PREFIX eio:    <http://w3id.org/def/emissionsInventoryOntology#>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX time:   <http://www.w3.org/2006/time#>
PREFIX saref:  <https://saref.etsi.org/core/>
PREFIX s4city: <https://saref.etsi.org/saref4city/>

SELECT ?city ?cityLabel ?unit (SUM(xsd:decimal(?value)) AS ?totalEmissionValue)

WHERE {
    VALUES ?pollutant {
        eio:CO2Scope1Emissions
    }

    VALUES ?year {
        "2022"^^xsd:gYear
    }

    ?emissionData
        rdf:type s4city:KeyPerformanceIndicatorAssessment ;
        s4city:quantifiesKPI ?pollutant ;
        s4city:refersToFeature ?city ;
        s4city:refersToTime ?period ;
        saref:hasValue ?value ;
        saref:isMeasuredIn ?unit .

    ?city rdf:type s4city:City .

    ?period
        rdf:type time:DateTimeInterval ;
        time:hasDateTimeDescription ?dateTimeDescription .

    ?dateTimeDescription
        rdf:type time:DateTimeDescription ;
        time:year ?year .

    OPTIONAL {
        ?city rdfs:label ?cityLabel .
        FILTER(
            LANG(?cityLabel) = "en" ||
            LANG(?cityLabel) = "es"
        )
    }
}
GROUP BY ?city ?cityLabel ?unit
ORDER BY DESC(?totalEmissionValue)
LIMIT 1